import p1 from '/src/assets/products/1.jpg';

export const products = [
  {
    id: 1,
    name: 'Civil War-Era Soldier\'s Compass',
    details: 'An authentic compass used by soldiers during the Civil War, with historical engravings and a leather carrying case.',
    description: 'Authentic Civil War Compass',
    category: 'Historical Artifacts',
    image: p1,
    stock: 1,
    new_price: 120,
    old_price: 150,
  },
  {
    id: 2,
    name: '1950s Tin Toy Robot',
    details: 'A classic tin toy robot from the 1950s, with wind-up functionality and retro-futuristic design.',
    description: 'Classic Tin Toy Robot',
    category: 'Toys and Games',
    image: p1,
    stock: 5,
    new_price: 40,
    old_price: 50,
  },
  {
    id: 3,
    name: 'Limited Edition Serigraph',
    details: 'A limited edition serigraph (silk screen print) signed and numbered by a contemporary artist, featuring vibrant and abstract compositions.',
    description: 'Contemporary Art Serigraph',
    category: 'Artworks',
    image: p1,
    stock: 3,
    new_price: 180,
    old_price: 200,
  },
  {
    id: 4,
    name: 'Rare Coin Collection Set',
    details: 'A curated set of rare coins from different historical periods, accompanied by a detailed information booklet.',
    description: 'Curated Rare Coin Set',
    category: 'Collectibles',
    image: p1,
    stock: 2,
    new_price: 100,
    old_price: 120,
  },
  {
    id: 5,
    name: 'Vintage Barbie Doll (1960s)',
    details: 'Original Barbie doll from the 1960s in good condition with original clothing and accessories.',
    description: '1960s Vintage Barbie Doll',
    category: 'Toys and Games',
    image: p1,
    stock: 10,
    new_price: 25,
    old_price: 300,
  },
  {
    id: 6,
    name: 'Nintendo Entertainment System',
    details: 'Complete NES gaming console in its original packaging with controllers and classic game cartridges.',
    description: 'Vintage Gaming Console',
    category: 'Toys and Games',
    image: p1,
    stock: 10,
    new_price: 30000,
    old_price: 23000,
  },
  {
    id: 7,
    name: 'Signed and Numbered Serigraph',
    details: 'Limited edition serigraph (silk screen print) signed and numbered by a contemporary artist.',
    description: 'Contemporary Art Serigraph',
    category: 'Artworks',
    image: p1,
    stock: 5,
    new_price: 100,
    old_price: 120,
  },
  {
    id: 8,
    name: 'Vintage Chess Set',
    details: 'Antique chess set with intricately designed pieces, showcasing craftsmanship.',
    description: 'Intricate Vintage Chess Set',
    category: 'Collectibles',
    image: p1,
    stock: 8,
    new_price: 75,
    old_price: 90,
  },
  {
    id: 9,
    name: 'Original World War II Gas Mask',
    details: 'Authentic World War II gas mask with its original packaging and historical documentation.',
    description: 'WWII Era Gas Mask',
    category: 'Historical Artifacts',
    image: p1,
    stock: 3,
    new_price: 150,
    old_price: 180,
  },
  {
    id: 10,
    name: 'Hand-Painted Ceramic Sculpture',
    details: 'Unique ceramic sculpture hand-painted by a local artist, showcasing intricate details and artistic expression.',
    description: 'Artistic Ceramic Sculpture',
    category: 'Artworks',
    image: p1,
    stock: 7,
    new_price: 100,
    old_price: 120,
  },
  {
    id: 11,
    name: 'Deluxe Edition Monopoly',
    details: 'Collectible edition of Monopoly with unique tokens, artwork, and game variations.',
    description: 'Monopoly Board Game Set',
    category: 'Toys and Games',
    image: p1,
    stock: 12,
    new_price: 45,
    old_price: 60,
  },
  {
    id: 12,
    name: 'Ancient Roman Silver Denarius',
    details: 'Authentic silver denarius from the Roman Empire, featuring a portrait of a historical figure.',
    description: 'Roman Empire Silver Coin',
    category: 'Historical Artifacts',
    image: p1,
    stock: 4,
    new_price: 190,
    old_price: 220,
  },
];
