import p1 from '/src/assets/products/1.jpg'

export const products = [
  {
    id: 1,
    name: 'StarBucks Holiday Cup',
    description: 'Limited Edition',
    category: 'Art',
    image: p1,
    new_price: 300,
    old_price: 25,
  },
  {
    id: 2,
    name: 'Woody',
    description: 'description',
    category: 'Toys',
    image: p1,
    new_price: 23000,
    old_price: 30000,
  },
  {
    id: 3,
    name: 'Mona Lisa',
    description: 'description',
    category: 'Art',
    image: p1,
    new_price: 300,
    old_price: 25,
  },
  {
    id: 4,
    name: 'Woody',
    description: 'description',
    category: 'Toys',
    image: p1,
    new_price: 23,
    old_price: 10,
  },

  {
    id: 5,
    name: 'Mona Lisa',
    description: 'description',
    category: 'Art',
    image: p1,
    new_price: 300,
    old_price: 25,
  },
  {
    id: 6,
    name: 'Woody',
    description: 'description',
    category: 'Toys',
    image: p1,
    new_price: 23,
    old_price: 10,
  },
  {
    id: 7,
    name: 'Woody',
    description: 'description',
    category: 'Toys',
    image: p1,
    new_price: 23,
    old_price: 10,
  },
  {
    id: 8,
    name: 'Woody',
    description: 'description',
    category: 'Toys',
    image: p1,
    new_price: 23,
    old_price: 10,
  },

];