import p99 from '/src/assets/products/99.jpg';
import p1 from '/src/assets/products/1.jpg';
import p2 from '/src/assets/products/2.jpg';
import p3 from '/src/assets/products/3.jpg';
import p4 from '/src/assets/products/4.jpg';
import p5 from '/src/assets/products/5.jpg';
import p6 from '/src/assets/products/6.jpg';

import p7 from '/src/assets/products/7.jpg';
import p8 from '/src/assets/products/8.jpg';
import p9 from '/src/assets/products/9.jpg';
import p10 from '/src/assets/products/10.jpg';
import p11 from '/src/assets/products/11.jpg';
import p12 from '/src/assets/products/12.jpg';
import p13 from '/src/assets/products/13.jpg';
import p14 from '/src/assets/products/14.jpg';

import p15 from '/src/assets/products/15.jpg';
import p16 from '/src/assets/products/16.jpg';
import p17 from '/src/assets/products/17.jpg';
import p18 from '/src/assets/products/18.jpg';
import p19 from '/src/assets/products/19.jpg';
import p20 from '/src/assets/products/20.jpg';

import p21 from '/src/assets/products/21.jpg';
import p22 from '/src/assets/products/22.jpg';
import p23 from '/src/assets/products/23.jpg';
import p24 from '/src/assets/products/24.jpg';
import p25 from '/src/assets/products/25.jpg';
import p26 from '/src/assets/products/26.jpg';
import p27 from '/src/assets/products/27.jpg';
import p28 from '/src/assets/products/28.jpg';
import p29 from '/src/assets/products/29.jpg';
import p30 from '/src/assets/products/30.jpg';
export const products = [
  {
    id: 1,
    name: 'Chongyun 8bit Controller',
    details: 'Immerse yourself in the pixelated world of Teyvat with the Chongyun Pixel Pro 8-bit Controller. This uniquely customized gaming accessory pays homage to the classic era of gaming while capturing the essence of Genshin Impact\'s frosty hero, Chongyun.',
    description: 'Game Controller',
    category: 'Tech & Gadgets',
    image: p1,
    stock: 1,
    new_price: 120,
    old_price: 150,
    featured: 'false',
  },
  {
    id: 2,
    name: 'Sony Playstation PS5 Console',
    details: 'The PS5™ console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and a all-new generation of incredible PlayStation® games. Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation® console can do.',
    description: 'Game Console',
    category: 'Tech & Gadgets',
    image: p2,
    stock: 5,
    new_price: 40,
    old_price: 50,
    featured: 'false',
  },
  {
    id: 3,
    name: 'XBOX Wireless Controller Gold Shadow',
    details: 'Elevate your gaming experience with the Xbox Wireless Controller Gold Shadow Edition. Immerse yourself in the sleek sophistication of its golden gradient design, casting a shadow that adds a touch of mystique to your gaming sessions. The textured grips ensure a comfortable and precise hold, while the wireless connectivity provides seamless control. With its striking aesthetics and advanced features, the Gold Shadow Edition transcends the ordinary, making every gaming moment a golden opportunity for victory.',
    description: 'Game Controller',
    category: 'Tech & Gadgets',
    image: p3,
    stock: 3,
    new_price: 180,
    old_price: 200,
    featured: 'false',
  },
  {
    id: 4,
    name: 'Meta Quest 3 VR Headset',
    details: 'Step into mixed reality with the 512GB version of the Meta Quest 3 Advanced All-in-One VR Headset. The third gen PC-free headset combines VR with AR, using dual RGB cameras to provide full-color passthrough into your real world surroundings. This can be used to insert games, screens, and other virtual objects into your environment. When it comes to VR, the Quest 3 has been redesigned inside and out to deliver the best Quest experience yet. Graphics power is doubled with a new XR2 Gen 2 Snapdragon processor. Visuals are sharper and smoother with a higher 2064 x 2208 resolution per eye at a 90 Hz refresh rate. Immersion extends to the Touch Plus controllers with TruTouch haptics, and everything is more comfortable with a lighter and 40% slimmer headset compared to the Quest 2.',
    description: 'VR Headset',
    category: 'Tech & Gadgets',
    image: p4,
    stock: 2,
    new_price: 100,
    old_price: 120,
    featured: 'false',
  },
  {
    id: 5,
    name: 'Midnight Black PS5 Controller',
    details: 'Discover a deeper gaming experience1 with the innovative new PS5™ controller. The DualSense wireless controller for PS5 offers immersive haptic feedback2, dynamic adaptive triggers2 and a built-in microphone, all integrated into an iconic design.  Feel physically responsive feedback to your in-game actions with dual actuators which replace traditional rumble motors. In your hands, these dynamic vibrations can simulate the feeling of everything from environments to the recoil of different weapons.',
    description: 'Game Controller',
    category: 'Tech & Gadgets',
    image: p5,
    stock: 10,
    new_price: 25,
    old_price: 300,
    featured: 'false',
  },
  {
    id: 6,
    name: 'PS4 DUALSHOCK 4 WIRELESS CONTROLLER',
    details: 'Precision control: The feel, shape, and sensitivity of the Dualshock 4\'s analog sticks and trigger buttons have been enhanced to offer players absolute control for all games on PlayStation 4 Sharing at your fingertips: The addition of the share button makes sharing your greatest gaming moments as easy as a push of a button. New ways to play: Revolutionary features like the touch pad, integrated light bar, and built in speaker offer exciting new ways to experience and interact with your games ',
    description: 'Game Controller',
    category: 'Tech & Gadgets',
    image: p6,
    stock: 10,
    new_price: 30000,
    old_price: 23000,
    featured: 'false',
  },

  {
    id: 7,
    name: 'BEE AND PUPPYCAT',
    details: 'Adulting is hard when you\'ve got bills to pay. While temp-work may not sound like much, things can get wild when you\'re traveling between dimensions. Wherever your quests take you, PuppyCat will be there to accompany you as this fun plush toy companion. Crafted with the utmost care and attention to detail, this soft character plushie will make your journey through Fishbowl Space extraordinary.',
    description: 'Cute Plushie',
    category: 'Toys and Games',
    image: p7,
    stock: 5,
    new_price: 100,
    old_price: 120,
    featured: 'false',
  },
  {
    id: 9,
    name: 'PUSHEEN THE CAT',
    details: 'A fellow student has seemingly vanished from the famous School of Witchcraft and Wizardry - and it is up to you to solve the mysterious disappearance. Playing as Harry, Ron, Hermione, Ginny, Luna or Neville, you must try and discover WHO did it, WHAT spell or item they used and WHERE the student was attacked. Move around Hogwarts making suggestions. But watch out! Wheels on the board will keep changing revealing secret passages, moving staircases or even the Dark Mark! Protection from the Dark Mark comes from the spells, allies and items provided by the Help Cards.',
    description: 'Board Game',
    category: 'Toys and Games',
    image: p9,
    stock: 3,
    new_price: 150,
    old_price: 180,
    featured: 'false',
  },
  {
    id: 11,
    name: 'Spongebob Plushie',
    details: 'Show off your love of Nickelodeon\'s SpongeBob SquarePants with this fun character plush! These 10-inch tall SpongeBob plush collectibles are sure to please fans of the popular animated series with their soft construction and absolutely adorable design. Collect them all! Officially licensed SpongeBob SquarePants plush collectible. Produced by Johnny\'s Toys.',
    description: 'Plushie',
    category: 'Toys and Games',
    image: p11,
    stock: 12,
    new_price: 45,
    old_price: 60,
    featured: 'false',
  },
  {
    id: 12,
    name: 'Patrick Star Plushie',
    details: 'Show off your love of Nickelodeon\'s SpongeBob SquarePants with this fun character plush! These SpongeBob plush are sure to please fans of the animated series with their soft construction and adorable design. Officially licensed. Produced by Chucks Toys.',
    description: 'Plushie',
    category: 'Toys and Games',
    image: p12,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 13,
    name: 'WE BARE BEARS GRIZZ',
    details: 'GUND is proud to present plush toys based on We Bare Bears, the hit Cartoon Network comedy about three brother bears and their adventures! This 12" plush version of Grizz features accurate details sure to please fans of the show. All three We Bare Bears (each sold separately) are stackable for easy display and added play value! As always, high-quality and huggable plush ensures this product will remain a favorite for years to come. Surface-washable for easy cleaning. Appropriate for ages one and up.',
    description: 'Plushie',
    category: 'Toys and Games',
    image: p13,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 14,
    name: 'WE BARE BEARS ICE BEAR',
    details: 'GUND is proud to present plush toys based on We Bare Bears, the hit Cartoon Network comedy about three brother bears and their adventures! This 12" plush version of Ice Bear features accurate details sure to please fans of the show. All three We Bare Bears (each sold separately) are stackable for easy display and added play value! As always, high-quality and huggable plush ensures this product will remain a favorite for years to come. Surface-washable for easy cleaning. Appropriate for ages one and up.',
    description: 'Plushie',
    category: 'Toys and Games',
    image: p14,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 10,
    name: 'Fast and Furious Die-cast vehicle',
    details: 'Jada Toys presents a new series of authentically detailed vehicles from the Fast & Furious franchise! This 1:24th scale vehicle measures approximately 8-inches long. Made of detailed die-cast metal with plastic construction, this amazing replica features opening doors and hood and real rolling wheels! Officially licensed, collect them all!',
    description: 'Toy Car',
    category: 'Toys and Games',
    image: p10,
    stock: 7,
    new_price: 100,
    old_price: 120,
    featured: 'false',
  },
  {
    id: 8,
    name: 'WORLD OF HARRY POTTER',
    details: 'Relive the magic of seeing Hogwarts School of Witchcraft and Wizardry for the first time while putting together this Harry Potter puzzle. Full color puzzle shows Hogwarts castle at night. 550-piece puzzle measures 18" x 24" when fully assembled. A perfect gift for Harry Potter fans!',
    description: '550-PIECE PUZZLE',
    category: 'Toys and Games',
    image: p8,
    stock: 8,
    new_price: 75,
    old_price: 90,
    featured: 'false',
  },

  // artworks
  {
    id: 15,
    name: 'Starry Night',
    details: 'Get a hand-painted museum-quality Reproduction of "Starry Night" by Vincent Van Gogh. The Reproduction will be hand-painted by one of our talented artists. "Starry Night" by Vincent Van Gogh Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p15,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 16,
    name: 'Mona Lisa',
    details: 'Get a hand-painted museum-quality Reproduction of "Mona Lisa (La Gioconda) c. 1503-05" by Leonardo Da Vinci. The Reproduction will be hand-painted by one of our talented artists. "Mona Lisa (La Gioconda) c. 1503-05" by Leonardo Da Vinci Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p16,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 17,
    name: 'Christ In The Storm On The Sea Of Galilee',
    details: 'Get a hand-painted museum-quality Reproduction of ""Christ In The Storm On The Sea Of Galilee" by Rembrandt van Rijn" by Rembrandt Van Rijn. The Reproduction will be hand-painted by one of our talented artists. ""Christ In The Storm On The Sea Of Galilee" by Rembrandt van Rijn" by Rembrandt Van Rijn Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p17,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 18,
    name: 'The Wanderer above the Mists',
    details: 'Get a hand-painted museum-quality Reproduction of "The Wanderer above the Mists 1817-18" by Caspar David Friedrich. The Reproduction will be hand-painted by one of our talented artists. "The Wanderer above the Mists 1817-18" by Caspar David Friedrich Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p18,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 19,
    name: 'Branches with Almond Blossom',
    details: 'Get a hand-painted museum-quality Reproduction of "Branches with Almond Blossom" by Vincent Van Gogh. The Reproduction will be hand-painted by one of our talented artists. "Branches with Almond Blossom" by Vincent Van Gogh Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p19,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 20,
    name: 'The Scream',
    details: 'Get a hand-painted museum-quality Reproduction of "The Scream" by Edvard Munch. The Reproduction will be hand-painted by one of our talented artists. "The Scream" by Edvard Munch Reproduction will come with a Free Certificate of Authenticity that verifies the authenticity of the hand-painted fine art reproduction you purchased.',
    description: 'Painting',
    category: 'Artworks',
    image: p20,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },

  //collectibles
  {
    id: 21,
    name: 'CARTMAN BRAH',
    details: 'Embrace the irreverent charm of South Park with the Cartman Brah Youtooz collectible. This figure captures Cartman in his iconic pose, complete with cheeky expression and distinctive hand gesture. Add a touch of animated mischief to your collection with this unique and humor-filled collectible.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p21,
    stock: 4,
    new_price: 190,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 22,
    name: 'GOOD TIMES WITH WEAPONS KYLE',
    details: 'Bring the South Park universe to life with the Weapons Kyle Youtooz collectible. This figure showcases Kyle wielding an array of weapons, capturing the essence of his adventurous spirit. Immerse yourself in the animated world of South Park and showcase your fandom with this detailed and dynamic Youtooz figure.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p22,
    stock: 8,
    new_price: 180,
    old_price: 210,
    featured: 'false',
  },
  {
    id: 23,
    name: 'GOOD TIMES WITH WEAPONS STAN',
    details: 'Complete your South Park Youtooz collection with the Weapons Stan figure. This collectible captures Stan armed and ready for mischief, showcasing his determined and adventurous personality. Whether you\'re a South Park fan or a collector of unique figures, Weapons Stan is a must-have addition to your display.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p23,
    stock: 12,
    new_price: 250,
    old_price: 220,
    featured: 'false',
  },
  {
    id: 24,
    name: 'PAJAMA CARTMAN',
    details: 'Step into the whimsical world of South Park with the Pajama Cartman Youtooz collectible. This figure features Cartman in cozy pajamas, capturing a playful and endearing moment from the animated series. Enhance your collection with this delightful and humorous representation of one of South Park\'s most iconic characters.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p24,
    stock: 15,
    new_price: 130,
    old_price: 160,
    featured: 'false',
  },
  {
    id: 25,
    name: 'CARTMAN WITH IMPLANTS',
    details: 'Bring laughter to your collection with the Cartman With Implants Youtooz figure. This collectible captures Cartman in a memorable moment featuring his distinctive "implants." Add a touch of humor and irreverence to your display with this unique South Park Youtooz collectible.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p25,
    stock: 6,
    new_price: 190,
    old_price: 170,
    featured: 'false',
  },
  {
    id: 26,
    name: 'NAIL ON HEAD PATRICK',
    details: 'Dive into the absurdity of SpongeBob SquarePants with the Nail on Head Patrick Youtooz figure. This collectible captures Patrick with a nail on his head, showcasing the humor and charm of the beloved character. Whether you\'re a SpongeBob fan or a collector of quirky figures, Nail on Head Patrick is a standout addition to any collection.',
    description: 'Youtooz',
    category: 'Collectibles',
    image: p26,
    stock: 10,
    new_price: 120,
    old_price: 150,
    featured: 'false',
  },
  {
    id: 27,
    name: 'IronMouse Plushie',
    details: 'Snuggle up with the IronMouse Plushie, a must-have for fans of virtual YouTubers. This adorable plushie features IronMouse in a huggable form, perfect for bringing a touch of virtual entertainment to your everyday life. Whether displayed on your shelf or used as a cuddly companion, the IronMouse Plushie is a delightful addition to any collection.',
    description: 'Plushie',
    category: 'Collectibles',
    image: p27,
    stock: 20,
    new_price: 80,
    old_price: 110,
    featured: 'false',
  },
  {
    id: 28,
    name: 'Avatar Appa',
    details: 'Embark on an adventure with the Avatar Appa plushie. This lovable plushie brings the magic of the animated series to life, featuring Appa, the iconic flying bison. Whether you\'re a fan of Avatar: The Last Airbender or simply adore adorable plushies, the Avatar Appa plushie is a charming addition to your collection.',
    description: 'Plushie',
    category: 'Collectibles',
    image: p28,
    stock: 5,
    new_price: 270,
    old_price: 240,
    featured: 'false',
  },
  {
    id: 29,
    name: 'Avatar Toph',
    details: 'Add a touch of Earthbending mastery to your collection with the Avatar Toph plushie. This plushie captures Toph Beifong, the iconic and feisty character from Avatar: The Last Airbender. Whether displayed on your shelf or used as a cuddly companion, the Avatar Toph plushie is a delightful addition for fans of the beloved animated series.',
    description: 'Plushie',
    category: 'Collectibles',
    image: p29,
    stock: 18,
    new_price: 150,
    old_price: 180,
    featured: 'false',
  },
  {
    id: 30,
    name: 'Spy x Family Bond',
    details: 'Immerse yourself in the world of "Spy x Family" with the Bond Figurine. This collectible captures a unique and heartwarming family bond from the popular manga series. Whether you\'re a manga enthusiast or a collector of figurines, the Spy x Family Bond Figurine is a captivating addition to your display, showcasing the intrigue and emotion of the series.',
    description: 'Figurine',
    category: 'Collectibles',
    image: p30,
    stock: 7,
    new_price: 200,
    old_price: 170,
    featured: 'false',
  },
];
